name: base22b
channels:
  - conda-forge
  - defaults
  - spyder-ide

dependencies:
  # Core scientific python libraries
  - python=3*
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pandas
  - statsmodels
  - sympy
  - pip

  - spyder=4*
  - spyder-notebook
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - ipywidgets
  - nb_conda_kernels
  - jupyterlab
  - ipympl
  - nodejs

  - seaborn
  - h5py
  - netcdf4
  - xarray
  - plotly

  - opencv
